version: '3.7'

networks:
  gis-network:
    name: gis-network
    driver: bridge

services:
  gis-sucursales-webapp:
    #build:
    #  context: ./
    #  dockerfile: Dockerfile
    image: gis/sucursales
    networks:
      - gis-network
    ports:
      - 8080:8080
    environment:
      #POSTGRES_JDBC_USER: UASENAME
      #POSTGRES_JDBC_PASS: PASSWORD
      SPRING_DATASOURCE_URL: "jdbc:postgresql://dbpostgis:5432/gisdb?currentSchema=public"
      #SPRING_PROFILES_ACTIVE: dev

    #command: mvn spring-boot:run -Dspring.profiles.active=dev
    depends_on:
      - dbpostgis

  dbpostgis:
    image: 'postgis/postgis:13-3.1'
    container_name: dbpostgis
    networks:
      - gis-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gisdb

  dbpostgis_test:
    image: 'postgis/postgis:13-3.1'
    container_name: dbpostgis_test
    networks:
      - gis-network
    #in-memory RAM database
    tmpfs:
      - /var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gisdb_test
